version: "3"
services:
  backend:
    image: flask-app-backend:latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
  frontend:
    image: nginx:alpine
    ports:
      - "300:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - backend